# Generated by Django 6.0 on 2025-12-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Bölge Adı')),
                ('city', models.CharField(max_length=50, verbose_name='Şehir')),
                ('altitude', models.IntegerField(verbose_name='Rakım (m)')),
                ('climate_type', models.CharField(max_length=50, verbose_name='İklim Tipi')),
                ('recorded_date', models.DateField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
            ],
        ),
        migrations.CreateModel(
            name='IrisPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sepal_length', models.FloatField(verbose_name='Çanak Yaprak Uzunluğu')),
                ('sepal_width', models.FloatField(verbose_name='Çanak Yaprak Genişliği')),
                ('petal_length', models.FloatField(verbose_name='Taç Yaprak Uzunluğu')),
                ('petal_width', models.FloatField(verbose_name='Taç Yaprak Genişliği')),
                ('species', models.CharField(max_length=50, verbose_name='Tür')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.location', verbose_name='Toplandığı Konum')),
            ],
        ),
    ]
